const DEFAULT_WIDTH = 3840;
const DEFAULT_HEIGHT = 2160;
const DEFAULT_FPS = 60;
const DEFAULT_DURATION_SECONDS = 30;
const DEFAULT_SETTLE_MS = 120;
const DEFAULT_VIRTUAL_TIME_BUDGET_MS = 1500;
const DEFAULT_LOAD_TIMEOUT_MS = 6500;
const DEFAULT_PREVIEW_FRAME_INTERVAL = 8;
const DEFAULT_OUTPUT_EXTENSION = ".mov";
const MOV_ENCODER = "prores_ks";
const MOV_PROFILE = "4444";
const MOV_PIXEL_FORMAT = "yuva444p10le";

const RESOLUTION_PRESETS = [
    { label: "3840 x 2160", width: 3840, height: 2160 },
    { label: "2560 x 1440", width: 2560, height: 1440 },
    { label: "1920 x 1080", width: 1920, height: 1080 }
];

const FPS_PRESETS = [24, 30, 60];

module.exports = {
    DEFAULT_DURATION_SECONDS,
    DEFAULT_FPS,
    DEFAULT_HEIGHT,
    DEFAULT_LOAD_TIMEOUT_MS,
    DEFAULT_OUTPUT_EXTENSION,
    DEFAULT_PREVIEW_FRAME_INTERVAL,
    DEFAULT_SETTLE_MS,
    DEFAULT_VIRTUAL_TIME_BUDGET_MS,
    DEFAULT_WIDTH,
    FPS_PRESETS,
    MOV_ENCODER,
    MOV_PIXEL_FORMAT,
    MOV_PROFILE,
    RESOLUTION_PRESETS
};
